"""v0.3 on_success hooks: the model writes a declarative task list, never commands.

Flow: task done → resume its session with `on_success` + OUTPUT_CONTRACT → extract
the JSON array → drop it in <home>/inbox/ → the scheduler's next loop ingests it.
Depth is capped at one: tasks generated by a hook cannot generate further tasks.
"""
import json
import shutil
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

from timetrace.db import Database
from timetrace.models import EV_HOOK_GENERATED, EV_HOOK_REJECTED, TOOLS

OUTPUT_CONTRACT = (
    "\n\nOutput contract (strict): reply with ONE JSON array and nothing else. Each element is an"
    ' object {"prompt": string, "tool": "claude" | "codex" | null, "any_tool": boolean}.'
    " Do not run commands, do not edit files, do not wrap the JSON in markdown fences."
)


def extract_tasks(text: str) -> List[Any]:
    """Return the first JSON array found anywhere in text."""
    dec = json.JSONDecoder()
    idx = text.find("[")
    while idx != -1:
        try:
            obj, _ = dec.raw_decode(text, idx)
        except ValueError:
            idx = text.find("[", idx + 1)
            continue
        if isinstance(obj, list):
            return obj
        idx = text.find("[", idx + 1)
    raise ValueError("no JSON array in hook output")


def validate(items: List[Any], max_tasks: int) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for it in items:
        if not isinstance(it, dict):
            continue
        prompt = it.get("prompt")
        if not isinstance(prompt, str) or not prompt.strip():
            continue
        tool = it.get("tool")
        if tool not in TOOLS:
            tool = None
        out.append({"prompt": prompt.strip(), "tool": tool, "any_tool": bool(it.get("any_tool"))})
        if len(out) >= max_tasks:
            break
    return out


def run_hook(db: Database, adapter, task: Dict[str, Any], home: Path, cfg: Dict[str, Any],
             now: int, log_file: str) -> Optional[Path]:
    """Ask the finished task's session for follow-up tasks; write them to the inbox."""
    if int(task.get("generation") or 0) >= 1:
        db.add_event(EV_HOOK_REJECTED, tool=task.get("tool"),
                     payload={"task_id": task["id"], "reason": "depth limit (generation>=1)"},
                     at=now)
        return None
    prompt = (task.get("on_success") or "").strip() + OUTPUT_CONTRACT
    try:
        res = adapter.resume(prompt, task["worktree"], task["session_id"], log_file)
    except Exception as exc:  # tool crashed; the parent task itself is already done
        db.add_event(EV_HOOK_REJECTED, tool=task.get("tool"),
                     payload={"task_id": task["id"], "reason": "hook run failed: %s" % exc}, at=now)
        return None
    if not res.ok:
        db.add_event(EV_HOOK_REJECTED, tool=task.get("tool"),
                     payload={"task_id": task["id"], "reason": res.error or "hook run not ok",
                              "blocked": res.blocked}, at=now)
        return None
    try:
        items = validate(extract_tasks(res.output), int(cfg.get("hook_max_tasks", 5)))
    except ValueError as exc:
        db.add_event(EV_HOOK_REJECTED, tool=task.get("tool"),
                     payload={"task_id": task["id"], "reason": str(exc),
                              "output": res.output[:500]}, at=now)
        return None
    inbox = Path(home) / "inbox"
    inbox.mkdir(parents=True, exist_ok=True)
    path = inbox / ("%d-%d.json" % (task["id"], now))
    path.write_text(json.dumps({"parent_id": task["id"], "generated_at": now, "tasks": items},
                               ensure_ascii=False, indent=2), encoding="utf-8")
    db.add_event(EV_HOOK_GENERATED, tool=task.get("tool"),
                 payload={"task_id": task["id"], "file": str(path), "count": len(items)}, at=now)
    return path


def ingest(db: Database, home: Path, cfg: Dict[str, Any], now: Optional[int] = None) -> int:
    """Turn inbox files into tasks. Files move to inbox/done or inbox/rejected."""
    now = now or int(time.time())
    inbox = Path(home) / "inbox"
    if not inbox.exists():
        return 0
    added = 0
    for path in sorted(p for p in inbox.iterdir() if p.is_file() and p.suffix == ".json"):
        reason = None
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            parent_id = int(data["parent_id"])
            parent = db.get_task(parent_id)
            if parent is None:
                reason = "parent %d not found" % parent_id
            elif int(parent.get("generation") or 0) >= 1:
                reason = "depth limit: parent generation >= 1"
            else:
                items = validate(data.get("tasks") or [], int(cfg.get("hook_max_tasks", 5)))
                if not items:
                    reason = "no valid tasks"
                else:
                    for it in items:
                        db.add_task(it["prompt"], parent["repo"], tool=it["tool"],
                                    any_tool=it["any_tool"], depends_on=parent_id,
                                    generation=int(parent.get("generation") or 0) + 1,
                                    parent_id=parent_id, now=now)
                        added += 1
        except (ValueError, KeyError, TypeError) as exc:
            reason = "invalid inbox file: %s" % exc
        dest = inbox / ("rejected" if reason else "done")
        dest.mkdir(parents=True, exist_ok=True)
        shutil.move(str(path), str(dest / path.name))
        if reason:
            db.add_event(EV_HOOK_REJECTED, payload={"file": path.name, "reason": reason}, at=now)
    return added
