"""Registering `timetrace statusline` as Claude Code's statusLine command.

~/.claude/settings.json gets `{"type": "command", "command": "<timetrace> statusline"}`
with the absolute timetrace launcher. When the user already has a status line
of their own, it is chained instead of replaced: a small generated script
(~/.timetrace/statusline-chain.sh) feeds the same stdin JSON to timetrace
(output discarded, failures ignored) and then to the original command, whose
output is what Claude Code shows. The original statusLine object is kept in
~/.timetrace/statusline-original.json (and the whole settings file is backed
up once), so `timetrace statusline --uninstall` puts it back exactly.
Re-installing never wraps twice.
"""
import json
import os
import re
import shlex
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

WRAPPER_NAME = "statusline-chain.sh"
ORIGINAL_NAME = "statusline-original.json"
BACKUP_SUFFIX = ".timetrace-backup"
# Our own direct command, including the pre-rename `keji statusline`.
_DIRECT = re.compile(r"(timetrace|keji|(^|[/\s'\"])tta)\S*['\"]?\s+statusline\s*$")


def settings_path(user_home: Path) -> Path:
    return Path(user_home) / ".claude" / "settings.json"


def wrapper_path(home: Path) -> Path:
    return Path(home) / WRAPPER_NAME


def _original_path(home: Path) -> Path:
    return Path(home) / ORIGINAL_NAME


def _load(path: Path) -> Dict[str, Any]:
    """settings.json as a dict; {} when missing. ValueError when it is not a JSON object."""
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8") or "{}")
    if not isinstance(data, dict):
        raise ValueError("not a JSON object")
    return data


def _write_json(path: Path, doc: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name("." + path.name + ".timetrace-tmp")
    tmp.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if path.exists():
        os.chmod(str(tmp), path.stat().st_mode & 0o777)
    os.replace(str(tmp), str(path))


def kind(status_line: Any, home: Path) -> Optional[str]:
    """"direct" / "wrapper" when the statusLine is ours, None otherwise."""
    if not isinstance(status_line, dict):
        return None
    command = str(status_line.get("command") or "").strip()
    wrapper = str(wrapper_path(home))
    if command in (wrapper, shlex.quote(wrapper)):
        return "wrapper"
    if _DIRECT.search(command):
        return "direct"
    return None


def installed(user_home: Path, home: Path) -> bool:
    try:
        return kind(_load(settings_path(user_home)).get("statusLine"), home) is not None
    except (OSError, ValueError):
        return False


def _wrapper_script(timetrace: str, original_command: str) -> str:
    return (
        "#!/bin/sh\n"
        "# timetrace statusline chain, generated by `timetrace statusline --install`.\n"
        "# `timetrace statusline --uninstall` restores your original statusLine.\n"
        "input=$(cat)\n"
        "# 1) timetrace records the quota; its output and any failure are ignored.\n"
        "printf '%%s' \"$input\" | %s statusline >/dev/null 2>&1 || true\n"
        "# 2) your original status line command gets the same input; its output is shown.\n"
        "printf '%%s' \"$input\" | /bin/sh -c %s\n"
    ) % (timetrace, shlex.quote(original_command))


def _write_wrapper(home: Path, timetrace: str, original_command: str) -> Path:
    path = wrapper_path(home)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_wrapper_script(timetrace, original_command), encoding="utf-8")
    os.chmod(str(path), 0o755)
    return path


def _backup_once(settings: Path) -> None:
    backup = settings.with_name(settings.name + BACKUP_SUFFIX)
    if settings.exists() and not backup.exists():
        backup.write_bytes(settings.read_bytes())


def install(user_home: Path, home: Path, timetrace_argv: List[str]) -> Tuple[str, str]:
    """Register the hook. Returns (result, detail): result is "installed",
    "chained", "unchanged" or "refused" (a statusLine that is not a command).
    Raises ValueError when settings.json is not valid JSON."""
    settings = settings_path(user_home)
    data = _load(settings)
    timetrace = " ".join(shlex.quote(part) for part in timetrace_argv)
    current = data.get("statusLine")
    ours = kind(current, home)
    if current is None or ours == "direct":
        new = dict(current or {})
        new.update({"type": "command", "command": "%s statusline" % timetrace})
        # A stale chain from an earlier install no longer applies.
        for leftover in (wrapper_path(home), _original_path(home)):
            if leftover.exists():
                leftover.unlink()
        result = "installed"
    elif ours == "wrapper":
        try:
            original = json.loads(_original_path(home).read_text(encoding="utf-8"))["statusLine"]
        except (OSError, ValueError, KeyError, TypeError):
            return "refused", "找不到原来的状态栏命令记录（%s）" % _original_path(home)
        _write_wrapper(home, timetrace, str(original.get("command") or ""))
        new = current
        result = "chained"
    else:
        if not isinstance(current, dict) or current.get("type", "command") != "command" or not current.get("command"):
            return "refused", "已有的 statusLine 不是命令，无法串联：%s" % json.dumps(current, ensure_ascii=False)
        Path(home).mkdir(parents=True, exist_ok=True)
        _write_json(_original_path(home), {"statusLine": current})
        wrapper = _write_wrapper(home, timetrace, str(current["command"]))
        new = dict(current)
        new["command"] = shlex.quote(str(wrapper))
        result = "chained"
    if new == current and settings.exists():
        return ("unchanged" if result == "installed" else result), str(settings)
    _backup_once(settings)
    data["statusLine"] = new
    _write_json(settings, data)
    return result, str(settings)


def uninstall(user_home: Path, home: Path) -> str:
    """Remove the hook, restoring a chained original. Returns "removed",
    "restored" or "absent". Raises ValueError on invalid settings JSON."""
    settings = settings_path(user_home)
    data = _load(settings)
    if kind(data.get("statusLine"), home) is None:
        return "absent"
    original = None
    try:
        original = json.loads(_original_path(home).read_text(encoding="utf-8")).get("statusLine")
    except (OSError, ValueError, AttributeError):
        original = None
    if original is not None:
        data["statusLine"] = original
    else:
        data.pop("statusLine", None)
    _write_json(settings, data)
    for leftover in (wrapper_path(home), _original_path(home)):
        if leftover.exists():
            leftover.unlink()
    return "restored" if original is not None else "removed"
